<a href="https://colab.research.google.com/github/devmendesm/DisciplinaInteligenciaArtificial/blob/main/Exercic%C3%ADos_DataScience_MatheusVinicius_6c_noturno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Crie um array unidimensional de 50 elementos contendo numeros inteiros aleatorios entre 10 e 100.
# importa a lib numpy e da o apelido np
import numpy as np

# o pacote random faz parte da numpy, sorteia um numero entre 10 e 100, com a quantidade de 50 numeros
array = np.random.randint(10, 101, 50)

# resultado é uma sequencia de valores com 50 elementos
print(array)

In [ ]:
# 2. Gere uma matriz 4x4 com numeros inteiros de 1 a 16 e extraia a ultima linha
# Utilizando a tecnica de fatiamento o -1 pega a ultima linha e o [:] pega todos elementos
import numpy as np

matriz = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

ultima_linha = matriz[-1, :]
print(ultima_linha)

In [ ]:
# 3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª a 10ª posicao por 1.
# np.zeros gera o array com 15 elementos 0, o fatiamento pega da posição 4 até a 9 e substitui por 1
import numpy as np

array = np.zeros(15)
array[4: 10] = 1

print(array)

In [ ]:
# 4. Gere um array de 100 numeros inteiros aleatorios e encontre a mediana e a moda dos valores.
import numpy as np

array = np.random.randint(1, 101, 100)
mediana = np.median(array)

# o unique armazena na variavel os valores unicos, e na quantidades, a quantia que se repetem, depois a argmax(),
# retorna o indice da onde foi o maior valor
valores, quantidades = np.unique(array, return_counts = True)
indice = np.argmax(quantidades)
moda = valores[indice]

print(array)
print(mediana)
print(moda)

In [ ]:
# 5. Crie um array de 20 elementos contendo numeros entre 1 e 100 e substitua todos os valores multiplos de 3 por -3.
import numpy as np

array = np.random.randint(1, 101, 20)
# utiliza do fatiamento com condição "no array onde o valor for multiplo de 3, coloque - 3"
array[array % 3 == 0] = -3
print(array)


In [ ]:
# 6. Gere uma matriz 5x5 de numeros aleatorios entre 0 e 1 e encontre a soma de cada coluna.
import numpy as np

matriz = np.random.rand(5, 5)
# utiliza o axis da np.sum() que = 0 soma somente as colunas separadamente
soma_colunas = np.sum(matriz, axis = 0)

print(matriz)
print("\nSoma de cada coluna: ", soma_colunas)

In [ ]:
# 7. Crie dois arrays de numeros aleatorios e encontre a correlacao entre eles.
import numpy as np

array1 = np.random.rand(10)
array2 = np.random.rand(10)

# Calcula a correlação dos 2 arrays. [0, 1] serve para pegar apenas a correlação entre os 2 arrays
correlacao = np.corrcoef(array1, array2)[0, 1]

print("Array 1: \n", array1)
print("Array 2: \n", array2)
print("Correlacao: \n", correlacao)


In [ ]:
# 8. Gere uma matriz 3x3 com numeros inteiros aleatorios e eleve todos os seus elementos ao quadrado.
import numpy as np

# gera a matriz 3x3 com inteiros de 1 até 11, depois eleva ao quadrado cada elemento (matriz ** 2)
matriz = np.random.randint(1, 11, (3, 3))
raiz = matriz ** 2

print(matriz)
print()
print(raiz)

In [ ]:
# 9. Crie um array com 10 numeros aleatorios e normalize seus valores entre 0 e 1.
import numpy as np

array = np.random.randint(1, 100, 10)
valor_minimo = np.min(array)
valor_maximo = np.max(array)

# a conta é feito em todos os elementos simultaneamente
normalizado = (array - valor_minimo) / (valor_maximo - valor_minimo)

print("Array original: \n", array)
print("Array normalizado: \n", normalizado)

In [ ]:
# 10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.
# Utiliza a função fill_diagonal() que serve para substituir os numeros da diagonal principal pelos desejados
import numpy as np

matriz = np.eye(6)
np.fill_diagonal(matriz, [1, 2, 3, 4, 5, 6])

print(matriz)


In [ ]:
# 11. Gere um array de 100 numeros inteiros e encontre o valor que mais se repete no array.
# o unique armazena na variavel os valores unicos, e na quantidades, a quantia que se repetem, depois a argmax(),
# retorna o indice da onde foi o maior valor
import numpy as np

array = np.random.randint(1, 101, 100)

valores, quantidades = np.unique(array, return_counts = True)
indice = np.argmax(quantidades)

moda = valores[indice]
quant = quantidades[indice]

print(array)
print(f"Valor que mais repete: {moda} = {quant} vezes")

In [ ]:
# 12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.
import numpy as np

matriz = np.random.randint(1, 20, (4, 4))
np.fill_diagonal(matriz, 7)

print(matriz)

In [ ]:
# 13. Crie um array contendo os 10 primeiros numeros pares e calcule sua soma cumulativa.
# gera uma sequencia apartir do 2, até o 20, pulando de 2 em 2
import numpy as np
array = np.arange(2, 21, 2)

# np.cumsum() se utiliza para fazer a soma cumulativa, retorna outro array com a soma
soma_cumulativa = np.cumsum(array)

print(array)
print("\nSoma: ", soma_cumulativa)

In [ ]:
# 14. Calcule a diferenca entre dois arrays de numeros aleatorios de mesmo comprimento e encontre a media das diferencas.
import numpy as np

array1 = np.random.randint(1, 11, 4)
array2 = np.random.randint(1, 11, 4)

# Subtrai elemente à elemento, e depois usa função para calcular a média
diferenca = array1 - array2
media = np.mean(diferenca)

print(f"Array1: {array1}\nArray2: {array2}")
print(f"Diferenca: {diferenca}")
print(f"Media: {media}")

In [ ]:
# 15. Gere um array contendo 20 numeros e substitua todos os valores maiores que 50 por 50.
import numpy as np

array = np.random.randint(1, 101, 20)
print("Array original: ", array)

array[array > 50] = 50

print("Array modifica: ", array)

In [80]:
# 16. Crie um array unidimensional e reorganize seus valores em uma matriz 3x4.
import numpy as np

# utiliza a função reshape() que serve para mudar o formato
array = np.random.randint(1, 50, 12)
matriz = array.reshape(3, 4)

print("Array: ", array)
print("Matriz: \n", matriz)

Array:  [ 9 14 17 30 32 34 43 48 37  1 48 45]
Matriz: 
 [[ 9 14 17 30]
 [32 34 43 48]
 [37  1 48 45]]


In [93]:
# 17. Gere uma matriz 4x4 de numeros inteiros aleatorios e multiplique cada valor por sua posicao na matriz.
import numpy as np

# crio uma matriz contendo as posições de 1 a 16 e multiplico os elementos da matriz com as respectivas posicoes
matriz = np.random.randint(1, 100, (4, 4))
posicoes = np.arange(1, 17).reshape(4, 4)

resultado = matriz * posicoes

print("matriz: \n", matriz)
print("Resultado da multiplicação: \n", resultado)

matriz: 
 [[14 54 60 25]
 [ 2 37 31 43]
 [21 22 79 63]
 [27  5 54 40]]
Resultado da multiplicação: 
 [[ 14 108 180 100]
 [ 10 222 217 344]
 [189 220 869 756]
 [351  70 810 640]]


In [97]:
# 18. Crie um array de 10 elementos contendo numeros entre 1 e 100 e substitua todos os valores multiplos de 5 por 0.
import numpy as np

array = np.random.randint(1, 101, 10)
print("Array original: ", array)

# condição para todos elementos que o resto da divisao por 5 for = 0 vao receber o valor 0
array[array % 5 == 0] = 0
print("Array modifica: ", array)

Array original:  [55 89 29 41 42 11 10 74 47 63]
Array modifica:  [ 0 89 29 41 42 11  0 74 47 63]


In [106]:
# 19. Crie dois arrays de numeros inteiros aleatorios de tamanho 20 e calcule o angulo entre eles (produto escalar normalizado).
import numpy as np

array1 = np.random.randint(1, 101, 20)
array2 = np.random.randint(1, 101, 20)

# pega o produto escalar com a função np.dot()
produto_escalar = np.dot(array1, array2)

# calcula a norma e o cosseno
norma1 = np.linalg.norm(array1)
norma2 = np.linalg.norm(array2)
cosseno = produto_escalar / (norma1 * norma2)

# a função np.arccos() retorna o arco-cosseno em radianos, ai transforma para graus
angulo = np.arccos(cosseno)
angulo_graus = np.degrees(angulo)

print("Array 1: ", array1)
print("Array 2: ", array2)
print("Produto escalar: ", produto_escalar)
print(f"Ângulo: {angulo_graus} graus" )

Array 1:  [50 97 81 88  6 18 44 23 10 52 40 74  9 20 45 77 51 61 31 11]
Array 2:  [43 36 91 22 59 21 78 45 82 95 49 51 33 19 42 35 90 75 43 64]
Produto escalar:  48106
Ângulo: 38.394696019443735 graus


In [119]:
# 20. Crie uma matriz de numeros inteiros e encontre o valor mınimo de cada linha.
import numpy as np

matriz = np.random.randint(1, 101, (4, 4))
minimos = np.min(matriz, axis = 1)

print("Matriz: \n", matriz)
print("Minimos: \n", minimos)

Matriz: 
 [[31  2 14  3]
 [20 53 68 19]
 [98 76 92 64]
 [97 56 12 84]]
Minimos: 
 [ 2 19 64 12]
