<a href="https://colab.research.google.com/github/devmendesm/DisciplinaInteligenciaArtificial/blob/main/Exercic%C3%ADos_DataScience_MatheusVinicius_6c_noturno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Crie um array unidimensional de 50 elementos contendo numeros inteiros aleatorios entre 10 e 100.
# importa a lib numpy e da o apelido np
import numpy as np

# o pacote random faz parte da numpy, sorteia um numero entre 10 e 100, com a quantidade de 50 numeros
array = np.random.randint(10, 101, 50)

# resultado é uma sequencia de valores com 50 elementos
print(array)

In [ ]:
# 2. Gere uma matriz 4x4 com numeros inteiros de 1 a 16 e extraia a ultima linha
# Utilizando a tecnica de fatiamento o -1 pega a ultima linha e o [:] pega todos elementos
import numpy as np

matriz = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

ultima_linha = matriz[-1, :]
print(ultima_linha)

In [ ]:
# 3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª a 10ª posicao por 1.
# np.zeros gera o array com 15 elementos 0, o fatiamento pega da posição 4 até a 9 e substitui por 1
import numpy as np

array = np.zeros(15)
array[4: 10] = 1

print(array)

In [ ]:
# 4. Gere um array de 100 numeros inteiros aleatorios e encontre a mediana e a moda dos valores.
import numpy as np

array = np.random.randint(1, 101, 100)
mediana = np.median(array)

# o unique armazena na variavel os valores unicos, e na quantidades, a quantia que se repetem, depois a argmax(),
# retorna o indice da onde foi o maior valor
valores, quantidades = np.unique(array, return_counts = True)
indice = np.argmax(quantidades)
moda = valores[indice]

print(array)
print(mediana)
print(moda)

In [ ]:
# 5. Crie um array de 20 elementos contendo numeros entre 1 e 100 e substitua todos os valores multiplos de 3 por -3.
import numpy as np

array = np.random.randint(1, 101, 20)
# utiliza do fatiamento com condição "no array onde o valor for multiplo de 3, coloque - 3"
array[array % 3 == 0] = -3
print(array)


In [ ]:
# 6. Gere uma matriz 5x5 de numeros aleatorios entre 0 e 1 e encontre a soma de cada coluna.
import numpy as np

matriz = np.random.rand(5, 5)
# utiliza o axis da np.sum() que = 0 soma somente as colunas separadamente
soma_colunas = np.sum(matriz, axis = 0)

print(matriz)
print("\nSoma de cada coluna: ", soma_colunas)

In [ ]:
# 7. Crie dois arrays de numeros aleatorios e encontre a correlacao entre eles.
import numpy as np

array1 = np.random.rand(10)
array2 = np.random.rand(10)

# Calcula a correlação dos 2 arrays. [0, 1] serve para pegar apenas a correlação entre os 2 arrays
correlacao = np.corrcoef(array1, array2)[0, 1]

print("Array 1: \n", array1)
print("Array 2: \n", array2)
print("Correlacao: \n", correlacao)


In [ ]:
# 8. Gere uma matriz 3x3 com numeros inteiros aleatorios e eleve todos os seus elementos ao quadrado.
import numpy as np

# gera a matriz 3x3 com inteiros de 1 até 11, depois eleva ao quadrado cada elemento (matriz ** 2)
matriz = np.random.randint(1, 11, (3, 3))
raiz = matriz ** 2

print(matriz)
print()
print(raiz)

In [123]:
# 9. Crie um array com 10 numeros aleatorios e normalize seus valores entre 0 e 1.
import numpy as np

array = np.random.randint(1, 100, 10)
valor_minimo = np.min(array)
valor_maximo = np.max(array)

# a conta é feito em todos os elementos simultaneamente
normalizado = (array - valor_minimo) / (valor_maximo - valor_minimo)

print("Array original: \n", array)
print("Array normalizado: \n", normalizado)

Array original: 
 [53 88 29  4 16 95 66 41 24  5]
Array normalizado: 
 [0.53846154 0.92307692 0.27472527 0.         0.13186813 1.
 0.68131868 0.40659341 0.21978022 0.01098901]


In [127]:
# 10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.
# Utiliza a função fill_diagonal() que serve para substituir os numeros da diagonal principal pelos desejados
import numpy as np

matriz = np.eye(6)
np.fill_diagonal(matriz, [1, 2, 3, 4, 5, 6])

print(matriz)


[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]
